# -*- coding: utf-8 -*-
"""evaluate_v2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13MWMMch0Vr-0NNTyNHfn7agZHPdU2Ih0
"""

import os
import torch
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from torch.utils.data import DataLoader
from torchvision import transforms
from sklearn.metrics import confusion_matrix, classification_report
from src.dataset import EngagementDataset
from src.model_v2 import EfficientNetB2

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
transform = transforms.Compose([
    transforms.Resize((260, 260)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

test_dataset = EngagementDataset("data/test.csv", transform)
test_loader = DataLoader(test_dataset, batch_size=32, num_workers=2, pin_memory=True)

model = EfficientNetB2()
model.load_state_dict(torch.load("models/final_model_v2.pth", map_location=device))
model = model.to(device).eval()

pred, true = [], []
with torch.no_grad():
    for images, labels in test_loader:
        images = images.to(device)
        outputs = model(images)
        _, p = torch.max(outputs, 1)
        pred.extend(p.cpu().numpy())
        true.extend(labels.numpy())

accuracy = np.mean(np.array(true) == np.array(pred))
print("Test Accuracy:", accuracy)

cm = confusion_matrix(true, pred)
plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=["Low","Medium","High"], yticklabels=["Low","Medium","High"])
plt.title("Confusion Matrix - V2")
plt.savefig("results/confusion_matrix_v2.png")
plt.close()

report = classification_report(true, pred, target_names=["Low","Medium","High"])
print(report)
with open("results/classification_report_v2.txt", "w") as f:
    f.write(report)