# -*- coding: utf-8 -*-
"""face_detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MhiPOQt93zL3tP4bdIfqURXe-a_gqqhS
"""

import cv2
import os

def crop_faces(input_folder, output_folder):
    detector = cv2.CascadeClassifier(
        cv2.data.haarcascades + "haarcascade_frontalface_default.xml"
    )
    os.makedirs(output_folder, exist_ok=True)
    for img_name in os.listdir(input_folder):
        img_path = os.path.join(input_folder, img_name)
        img = cv2.imread(img_path)

        if img is None:
            continue

        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        faces = detector.detectMultiScale(gray, 1.3, 5)

        for (x, y, w, h) in faces:
            face = img[y:y+h, x:x+w]
            cv2.imwrite(os.path.join(output_folder, img_name), face)
            break