# -*- coding: utf-8 -*-
"""preprocessing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12WhVRl8c5fcwifTbjvka7D0IVXclx8pt
"""

import cv2
import os

def preprocess_images(input_folder, output_folder):
    os.makedirs(output_folder, exist_ok=True)
    for img_name in os.listdir(input_folder):
        img_path = os.path.join(input_folder, img_name)
        img = cv2.imread(img_path)

        if img is None:
            continue

        img = cv2.resize(img, (224, 224))
        cv2.imwrite(os.path.join(output_folder, img_name), img)